vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
       artworks:
           uri_prefix: /uploads/artworks
           upload_destination: '%kernel.project_dir%/public/uploads/artworks'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer